### ISSUE TITLE
Doesn't work for tabs

### ISSUE THREAD

**Issue by crabvk** [CreativeBulma/bulma-badge#1]
> easily display a badge attached to <u>**any**</u> kind of element, in different position

Not true.
![](https://i.imgur.com/xUXkJRl.png)

```html
<div class="tabs">
  <ul>
    <li class="is-active"><a href="#">Tab1</a></li>
    <li>
      <a href="#">
        <span class="badge is-right">42</span>
        Tab2
      </a>
    </li>
  </ul>
</div>

<div>
  <p>Dolorum accusantium ut reprehenderit sint harum hic est?<br>
  Molestias adipisci suscipit quo.<br>
  Et et est qui qui fugiat et.<br>
  Ea consequatur fuga doloribus.<br>
  Est et laudantium ut voluptas eius rem officia in ipsam?</p>
</div>
```

**Comment by CreativeBulma** [comment]
Hi @vyachkonovalov,

Thanks for noticing the bug.
This is related to the fact that Tabs are missing <code>position: relative</code> css rule.

You can easily fix it by adding the following code to your project.

**CSS**
```css
.tabs a {
  position: relative;
}
```

**SASS**
```sass
.tabs a
    position: relative
```

regards,

**Comment by crabvk** [comment]
@CreativeBulma thank you.
