### ISSUE TITLE
SASS division without slash

### ISSUE THREAD

**Issue by christopherpickering** [CreativeBulma/bulma-badge#7]
There are a lot of warnings when compiling the sass. The same problem as jgthms/bulma#3333.

Is it possible to get an update?

**Comment by CreativeBulma** [comment]
fixed by Update index.sass #8

**Comment by t4traw** [comment]
Nice work!
When will this be updated in npm?

**Comment by ThisFunctionalTom** [comment]
Hi,

could you please publish a new version containing this fix as npm package on npmjs.com?

Thanks in advance 😊
